version: 2.1

setup: true

executors:
  default:
    docker:
      - image: 'cimg/clojure:1.11-node'

orbs:
  continuation: circleci/continuation@0.3.1

jobs:
  setup:
    executor: default
    steps:
      - checkout # checkout code
      - run: # run a command
          name: Generate config
          command: |
            clojure -T:build generate-ci-config
      - continuation/continue:
          configuration_path: generated-config.yml # use newly generated config to continue

workflows:
  setup:
    jobs:
      - setup
